# -*- coding: utf-8 -*-
"""The hand bottles' figures (round seven, 2026-09-27): the brand's picture drawn at the hand's own
resolution, not the cellar's mark blown up. The author: "düz bir etiket üstü şekil olmasın, desenler
figürler olsun". Each is a grid of symbols and a colour for each symbol; '.' is the paper.

Drawn in the shelf style's one hand: a dark contour (k), the body in two or three steps of one ramp lit
from the upper left, one highlight. Palette names are the project's ramps (Tools/v4_bottles/palette.py).
"""

# symbol -> palette 'RampN'; 'k' defaults to the label's ink when a figure leaves it out
FIG = {
    'crown': ([
        "..k.......k.......k..",
        ".kwk.....kwk.....kwk.",
        "..k.......k.......k..",
        "..kk.....kak.....kk..",
        "..kak...kAaak...kak..",
        "..kAak.kAaaadk.kAak..",
        "..kAaakAaaaaadkAaak..",
        "..kAaaaaaaaaaaaaadk..",
        "..kAaaaaaaaaaaaaadk..",
        "..kkkkkkkkkkkkkkkkk..",
        "..kArAAbAAwAAbAArAk..",
        "..kdddddddddddddddk..",
        "..kkkkkkkkkkkkkkkkk..",
    ], {'k': 'Malt0', 'A': 'Amber4', 'a': 'Amber3', 'd': 'Amber2', 'r': 'ViceRed2', 'b': 'ClubBlue3',
        'w': 'Cream4'}),

    'crown_small': ([
        "k....k....k",
        "kk..kak..kk",
        "kak.kak.kak",
        "kaakaaakaak",
        "kaaaaaaaaak",
        "kkkkkkkkkkk",
        "kararwarark",
        "kkkkkkkkkkk",
    ], {'k': 'Malt0', 'a': 'Amber3', 'r': 'ViceRed2', 'w': 'Cream4'}),

    'cameo': ([
        "....kkkk...",
        "...kkkkkk..",
        "..kkkkkkkk.",
        "..kkkkkkkk.",
        "..kkkkkkkkk",
        "...kkkkkkk.",
        "...kkkkkkk.",
        "....kkkkk..",
        ".....kkk...",
        "....kkkkk..",
        "..kkkkkkkkk",
        ".kkkkkkkkkk",
    ], {}),

    'goose': ([
        "k.........k",
        "kk.......kk",
        ".kk.....kk.",
        "..kkk.kkk..",
        "...kkkkk...",
        "....kkkaa..",
        ".....k.....",
    ], {'a': 'Amber3'}),

    'whale': ([
        "..........w.w.........",
        "...........w..........",
        "..........w.w.........",
        "......................",
        "....kkkkkkkkk.........",
        "..kkbbbbbbbbbkk....kk.",
        ".kbBBbbbbbbbbbbk..kbk.",
        "kbBwkbbbbbbbbbbbkkbbk.",
        "kbbbbbbbbbbbbbbbbbbk..",
        "kcccccbbbbbbbbbbbbk...",
        ".kcccccccbbbbbbkkk....",
        "..kkkkkkkkkkkkk.......",
    ], {'k': 'ClubBlue0', 'b': 'ClubBlue2', 'B': 'ClubBlue3', 'c': 'ClubBlue4', 'w': 'Cream4'}),

    'pineapple': ([
        "...k.k.k...",
        "..kgkgkgk..",
        "...kgGgk...",
        ".k.kgGgk.k.",
        "kgkkgGgkkgk",
        ".kgggGgggk.",
        "..kkkkkkk..",
        ".kyYyYyYyk.",
        "kyYyYyYyYyk",
        "kYyYyYyYyYk",
        "kyYyYyYyYyk",
        "kYyYyYyYyYk",
        ".kyYyYyYyk.",
        "..kkkkkkk..",
    ], {'g': 'Lime1', 'G': 'Lime2', 'y': 'Amber3', 'Y': 'Amber2'}),

    'juniper': ([
        "........k........",
        ".......kgk.......",
        "......kgGgk......",
        "..k...kgGgk...k..",
        ".kgk..kgGgk..kgk.",
        ".kgGk.kgGgk.kGgk.",
        "..kgGkkgGgkkGgk..",
        "...kgGkgGgkGgk...",
        "....kkkgGgkkk....",
        "..kkk..kgk..kkk..",
        ".kbBbk.kgk.kbBbk.",
        ".kbbbk.kgk.kbbbk.",
        "..kkk.kbbbk.kkk..",
        "......kbBbbk.....",
        "......kbbbbk.....",
        ".......kkkk......",
    ], {'g': 'Lime1', 'G': 'Lime3', 'b': 'ClubBlue1', 'B': 'ClubBlue3'}),

    'rose': ([
        "....kkkkk....",
        "..kkrRRrrkk..",
        ".krRRrrrRrrk.",
        ".krRrkkkrRrk.",
        "krRrkrrrkrRrk",
        "krrRkrRrkRrrk",
        ".krrRkkkRrrk.",
        ".kkrrrRrrrkk.",
        "kgkkkrrrkkkgk",
        "kGgk.kkk.kgGk",
        ".kGgk.g.kgGk.",
        "..kkk.g.kkk..",
        "......gk.....",
        ".....kg......",
        "......g......",
        "......gk.....",
        "......g......",
    ], {'r': 'ViceRed2', 'R': 'ViceRed3', 'g': 'Lime1', 'G': 'Lime2'}),

    'gibbon': ([
        "....kkkkkkk....",
        "...kbbbbbbbk...",
        "..kbBbbbbbbbk..",
        ".kkbbwwbwwbbkk.",
        "kwkbwwwwwwwbkwk",
        "kwkbwkwwwkwbkwk",
        "kwkbwwwwwwwbkwk",
        ".kkbbwwkwwbbkk.",
        "...kbwwwwwbk...",
        "...kbwkkkwbk...",
        "....kbwwwbk....",
        ".....kkkkk.....",
    ], {'b': 'Malt1', 'B': 'Malt2', 'w': 'Amber4'}),

    'bat': ([
        "k..........k.k..........k",
        "kk.........kkk.........kk",
        "knk.......kkkkk.......knk",
        "knnkk....kkkkkkk....kknnk",
        "kkknnkkkkkkkkkkkkkkknnkkk",
        ".kkkknkkkkkkkkkkkkknkkkk.",
        "..kkkknkkkkkkkkkkknkkkk..",
        "...kkk.kkkkkkkkkkk.kkk...",
        "....k....kkkkkkk....k....",
        "..........kkkkk..........",
        "...........kkk...........",
    ], {'k': 'Night1', 'n': 'Night3'}),

    'anchor': ([
        "......kkk......",
        ".....kk.kk.....",
        "......kkk......",
        ".......k.......",
        "...kkkkkkkkk...",
        ".......k.......",
        "..y....k....y..",
        ".y.y...k...y.y.",
        "..y.y..k..y.y..",
        "....y..k..y....",
        ".......k.......",
        "k......k......k",
        "kk.....k.....kk",
        ".kk....k....kk.",
        "..kkk..k..kkk..",
        "....kkkkkkk....",
        "......kkk......",
    ], {'y': 'Amber2'}),

    'volcano': ([
        "......c.cc.c...........",
        ".....cCcCccCc..........",
        "......cCCcCc...........",
        "........cCc............",
        "........rRr............",
        ".......rRyRr...........",
        "........rRr............",
        ".......kkRkk...........",
        "......kmmRmmk..........",
        ".....kmmrRrmmk.........",
        "....kMmmmRmmmmk........",
        "...kMMmmmrmmmmmk.......",
        "..kMMmmmmmmmmmmmk......",
        ".kMMmmmmmmmmmmmmmk.....",
        "kMMmmmmmmmmmmmmmmmk....",
        "kkkkkkkkkkkkkkkkkkkk...",
    ], {'c': 'Graphite4', 'C': 'Cream3', 'r': 'ViceRed2', 'R': 'Amber3', 'y': 'Amber4',
        'm': 'Night3', 'M': 'Night4'}),

    'palm': ([
        "....gg.....gg......",
        "..ggGGg...gGGgg....",
        ".gg..gGg.gGg..gg...",
        "g.....gGkGg.....g..",
        ".....gg.k.gg.......",
        "....g...k...g......",
        ".........k.........",
        ".........k.........",
        ".........k.........",
        "........kk.........",
        "........k..........",
        "........k..........",
        ".......kkk.........",
        "..kkkkkkkkkkkkk....",
    ], {'g': 'Lime1', 'G': 'Lime2', 'k': 'Malt0'}),

    'walker': ([
        "....kkk......",
        "....kkk......",
        "...kkkkk.....",
        "....kwk......",
        "....kkk......",
        "...kkkkk.....",
        "..kkkkkkk....",
        "..kkkkkkkk...",
        "..kkkkkk.kk..",
        "..kkkkkk..k..",
        "..kkkkkkk.k..",
        "..kk.kkkk.k..",
        "..k...kkk.k..",
        "..k...k.k.k..",
        ".k....k..kk..",
        ".k....k...k..",
        "kk...kk...k..",
    ], {}),

    'spaniel': ([
        ".....kkkkk.......",
        "...kkbbbbbkk.....",
        "..kbbBbbbbbbk....",
        "..kbbbbbbwkbbk...",
        ".kbbbbbbbbbbbbk..",
        ".kddbbbbbbbbbbbkk",
        "kdddbbbbbbbbbbbbk",
        "kddddbbbbbbkkkknk",
        "kddddkbbbbbk.....",
        "kddddk.kbbk......",
        "kddddk..kk.......",
        ".kdddk...........",
        "..kdk............",
        "...k.............",
    ], {'b': 'Cream4', 'B': 'Cream4', 'd': 'Cream2', 'w': 'Night1', 'n': 'Night1', 'k': 'Cream1'}),

    'star': ([
        ".....k.....",
        "....kak....",
        "....kak....",
        "kkkkaaakkkk",
        ".kaaaaaaak.",
        "..kaaaaak..",
        "..kaaaaak..",
        ".kaaakaaak.",
        ".kaak.kaak.",
        ".kk.....kk.",
    ], {'a': 'ViceRed2'}),

    'acorn': ([
        "........kk.......",
        ".......kmk.......",
        ".....kkkkkkk.....",
        "...kkCcCcCcCkk...",
        "..kCcCcCcCcCcCk..",
        "..kcCcCcCcCcCck..",
        "..kkkkkkkkkkkkk..",
        "...kaAaaaaaaadk..",
        "...kAaaaaaaaadk..",
        "...kAaaaaaaaadk..",
        "....kAaaaaaadk...",
        ".....kaaaaadk....",
        "......kaaadk.....",
        ".......kkkk......",
    ], {'m': 'Malt1', 'C': 'Malt1', 'c': 'Malt2', 'A': 'Amber4', 'a': 'Amber3', 'd': 'Amber2'}),

    'oakleaf': ([
        "...kk....",
        "..kgGk...",
        ".kgGGgkk.",
        "kgGGggggk",
        ".kgGgggk.",
        "kgGggggk.",
        ".kgggggk.",
        "..kgggk..",
        "...kgk...",
        "....k....",
    ], {'g': 'Lime1', 'G': 'Lime2'}),

    'crow': ([
        ".........kkk.....",
        "........kkwkk....",
        ".......kkkkkkaa..",
        "......kkkkkkk....",
        ".....knkkkkkk....",
        "...kknkkkkkk.....",
        ".kknkkkkkkkk.....",
        "kknkkkkkkkk......",
        "..kkkkkkkk.......",
        ".....kk.k........",
        ".....y..y........",
        "..mmmmmmmmmmmm...",
    ], {'n': 'Night3', 'a': 'Amber3', 'y': 'Amber3', 'm': 'Malt1', 'w': 'Cream4'}),

    'agave': ([
        "..........k..........",
        "....k.....g.....k....",
        ".....g....G....g.....",
        "..k...g..gGg..g...k..",
        "...g..gG.gGg.Gg..g...",
        "....g..gGgGgGg..g....",
        ".k...gG.ggGgg.Gg...k.",
        "..gg..gGgggggGg..gg..",
        "...gGg.ggGGGgg.gGg...",
        "....gggGgGGGgGggg....",
        ".....ggggggggggg.....",
        "......kkkkkkkkk......",
    ], {'g': 'Lime1', 'G': 'Lime3'}),

    'ship': ([
        ".........k.........",
        ".........krr.......",
        ".........k.........",
        "....o....k.........",
        "...owo...k...o.....",
        "...owwo..k..owo....",
        "..owwwo.ok..owwo...",
        "..owwwwoowk.owwwo..",
        ".owwwwwowwk.owwwwo.",
        ".ooooooooookoooooo.",
        ".........k.........",
        "kkkkkkkkkkkkkkkkkkk",
        ".kbbbbbbbbbbbbbbbk.",
        "..kbbbbbbbbbbbbbk..",
        "...kkkkkkkkkkkkk...",
        ".ll..ll..ll..ll..l.",
        "l..ll..ll..ll..ll..",
    ], {'w': 'Cream4', 'o': 'Cream1', 'r': 'ViceRed2', 'b': 'ClubBlue2', 'l': 'ClubBlue3'}),

    'koala': ([
        ".kkk.........kkk.",
        "kgggk.......kgggk",
        "kgwggkkkkkkkggwgk",
        "kgggggggggggggggk",
        ".kggggggggggggGk.",
        "..kggkkgggkkggk..",
        "..kggkwgggkwggk..",
        "..kgggggkgggggk..",
        "...kgggkkkgggk...",
        "...kggkkkkkggk...",
        "....kggkkkggk....",
        ".....kgggggk.....",
        "......kkkkk......",
    ], {'g': 'Graphite3', 'G': 'Graphite2', 'w': 'Cream3'}),

    'branch': ([
        "..g.....g......g...",
        ".gGg...gGg....gGg..",
        "..gmm..gm....mgm...",
        "mmmmmmmmmmmmmmmmmmm",
        ".....gm....mg......",
        "....gGg....gGg.....",
        ".....g......g......",
    ], {'g': 'Lime1', 'G': 'Lime2', 'm': 'Malt1'}),

    'boot': ([
        "...kkkkkkk......",
        "...kbBbbbk......",
        "...kbBbbbk......",
        "...kbBbbbk......",
        "...kbBbbbk......",
        "...kbBbbbk......",
        "...kbBbbbbkkk...",
        "..kbBbbbbbbbbkk.",
        "..kbbbbbbbbbbbbk",
        "..kkkkkkkkkkkkkk",
        "..kyykyykyykyyk.",
        "...kkkkkkkkkkk..",
    ], {'b': 'Malt1', 'B': 'Malt2', 'y': 'Amber2'}),

    'cottage': ([
        "..............ss...",
        ".............s..s..",
        "..............ss...",
        ".......k.....kk....",
        "......kRk....kk....",
        ".....kRRRk...kk....",
        "....kRRRRRk..kk....",
        "...kRRRRRRRk.kk....",
        "..kRRRRRRRRRkkk....",
        ".kRRRRRRRRRRRRk....",
        "kkkkkkkkkkkkkkkk...",
        ".kcccccccccccck....",
        ".kckkkcccckkkck....",
        ".kckykcccckykck....",
        ".kckkkcccckkkck....",
        ".kccccckkkcccck....",
        ".kccccckykcccck....",
        ".kkkkkkkkkkkkkk....",
    ], {'s': 'Graphite4', 'R': 'Brick2', 'c': 'Cream3', 'y': 'Amber4'}),

    'pomegranate': ([
        ".....k.k.k.....",
        ".....kRkRk.....",
        "......kRk......",
        "....kkkkkkk....",
        "..kkrrRRrrrkk..",
        ".krrRRwRrrrrrk.",
        ".krRRwRrrrrrrk.",
        "krrRRRrrrrrrrdk",
        "krrRRrrrrrrrrdk",
        "krrrrrrrrrrrddk",
        "krrrrrrrrrrrddk",
        ".krrrrrrrrrddk.",
        ".kdrrrrrrrdddk.",
        "..kkddddddddk..",
        "....kkkkkkk....",
    ], {'k': 'ViceRed0', 'r': 'ViceRed2', 'R': 'ViceRed3', 'w': 'ViceRed4', 'd': 'ViceRed1'}),

    'ox': ([
        "k.................k",
        "kk...............kk",
        ".kk.............kk.",
        "..kkk...kkk...kkk..",
        "...kkkkkrrrkkkkk...",
        "....krrrrrrrrrk....",
        "....krkkrrrkkrk....",
        "....krrrrrrrrrk....",
        ".....krrrrrrrk.....",
        ".....krrwwwrrk.....",
        "......krwkwrk......",
        ".......kkkkk.......",
    ], {'k': 'Night1', 'r': 'ViceRed2', 'w': 'ViceRed4'}),

    'bolt': ([
        "...kkk",
        "..kyk.",
        ".kyk..",
        "kyyyk.",
        ".kyk..",
        "kyk...",
        "kk....",
    ], {'y': 'Amber4'}),

    'leaf': ([
        "....kk",
        "..kkgk",
        ".kgGgk",
        "kgGgk.",
        "kggk..",
        ".kk...",
    ], {'g': 'Lime1', 'G': 'Lime3'}),

    'ginger': ([
        "..kk.....kk..",
        ".kyyk...kyyk.",
        ".kyYykkkyYyk.",
        "..kyYyyyyyk..",
        "...kyyYyyk...",
        "..kyyyyyyyk..",
        ".kyYk.kyYyk..",
        ".kyk...kkk...",
        "..k..........",
    ], {'y': 'Amber3', 'Y': 'Amber4', 'k': 'Malt1'}),
}


def grid(name):
    rows, cmap = FIG[name]
    w = max(len(r) for r in rows)
    return [r.ljust(w, '.') for r in rows], cmap
