using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using LastCall.Core;
using LastCall.Game;
using UnityEditor;
using UnityEngine;

namespace LastCall.EditorTools
{
    /// <summary>
    /// Writes <c>Docs/BALANCE.md</c>: every price in the game, and what each one is worth in
    /// money and in stars.
    ///
    /// The author, 2026-08-11: a guide to how the drinks, the garnishes and the rest feed the
    /// prices and the rating, so a balance change can be judged before it is made.
    ///
    /// It is GENERATED, and that is the whole point. A hand-written balance doc is a snapshot
    /// of what somebody believed on the day they wrote it, and this project has already been
    /// bitten by one — the sim caught two design bugs and two reporting bugs that a document
    /// would have kept repeating. Every number here is read from the code and the data that
    /// actually decide it: the JSON under Assets/Data, DrinkOrder.MenuPrice, ServiceJudge's
    /// weights, BarRating's curve, TycoonConfig's costs. Change any of them and re-run this;
    /// if a number here is wrong, the game is wrong, not the document.
    ///
    /// It deliberately does NOT simulate. <c>LastCall → Simulate Tycoon 200 Runs</c> answers
    /// what happens; this answers what things are worth, which is the question you have when
    /// you are about to change one.
    /// </summary>
    public static class BalanceGuide
    {
        private const string DeckPath = "Assets/Data/bottles/base_bar.json";
        private const string RecipesPath = "Assets/Data/recipes/recipes.json";
        private const string GlasswarePath = "Assets/Data/glassware/glassware.json";
        private const string OutPath = "Docs/BALANCE.md";

        private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

        [MenuItem("LastCall/Write Balance Guide")]
        public static void Write()
        {
            var deck = DataLoader.ParseDeck(Load(DeckPath));
            var recipes = DataLoader.ParseRecipes(Load(RecipesPath));
            var glassware = DataLoader.ParseGlassware(Load(GlasswarePath));
            var config = new TycoonConfig();

            var sb = new StringBuilder();
            Header(sb);
            OneServe(sb, config);
            Drinks(sb, recipes, glassware);
            Craft(sb, deck);
            Stars(sb);
            Shelf(sb, deck, config);
            Night(sb, config);
            Footer(sb);

            Directory.CreateDirectory(Path.GetDirectoryName(OutPath));
            File.WriteAllText(OutPath, sb.ToString(), new UTF8Encoding(false));
            AssetDatabase.Refresh();
            Debug.Log($"Balance guide written to {OutPath} — {recipes.Count} drinks, "
                      + $"{deck.Cards.Count} shelf items.");
        }

        private static string Load(string path)
        {
            var asset = AssetDatabase.LoadAssetAtPath<TextAsset>(path);
            if (asset == null) throw new FileNotFoundException(path);
            return asset.text;
        }

        // ── the sheets ──────────────────────────────────────────────────────────

        private static void Header(StringBuilder sb)
        {
            sb.AppendLine("# LAST CALL — what everything is worth");
            sb.AppendLine();
            sb.AppendLine("Generated by **LastCall → Write Balance Guide**. Every number below is read");
            sb.AppendLine("out of the code and data that decide it — change a weight or a price and");
            sb.AppendLine("re-run this rather than editing the page.");
            sb.AppendLine();
            sb.AppendLine("For what actually *happens* over a run, use **LastCall → Simulate Tycoon");
            sb.AppendLine("200 Runs** (`Docs/tycoon_sim_report.md`). This page answers what a thing is");
            sb.AppendLine("worth; that one answers whether the game is playable at those worths.");
            sb.AppendLine();
        }

        private static void OneServe(StringBuilder sb, TycoonConfig config)
        {
            sb.AppendLine("## One serve, from top to bottom");
            sb.AppendLine();
            sb.AppendLine("```");
            sb.AppendLine("  paid   = menu price × (" + F(ServiceJudge.AccuracyPayFloor) + " + "
                          + F(1 - ServiceJudge.AccuracyPayFloor) + " × accuracy)   closeness to the");
            sb.AppendLine("           recipe's perfect pour (21 §9a) — the right box always earns");
            sb.AppendLine("           something; the WRONG drink pays what is actually in the glass,");
            sb.AppendLine("           and their drink OUT OF ITS BOX pays nothing at all");
            sb.AppendLine("  tip    = paid × " + F(ServiceJudge.TipCeiling) + " × quality");
            sb.AppendLine();
            sb.AppendLine("  quality = " + F(ServiceJudge.SpeedWeight) + " × speed"
                          + "      how much patience was left when it landed");
            sb.AppendLine("          + " + F(ServiceJudge.SpecWeight) + " × craft"
                          + "      what they asked for, and how the book says to work it");
            sb.AppendLine("          + " + F(ServiceJudge.AccuracyWeight) + " × accuracy"
                          + "   the pour against the perfect, again — bill AND thanks");
            sb.AppendLine("          + " + F(ServiceJudge.FillWeight) + " × fill"
                          + "       how close the glass came to " + P(ServingSpec.NormalFill));
            sb.AppendLine();
            sb.AppendLine("  craft   = " + F(ServiceJudge.GarnishShare) + " × their asks"
                          + "  the garnishes on the licence, each all-or-nothing");
            sb.AppendLine("          + " + F(ServiceJudge.MethodShare) + " × the method"
                          + "  shaken recipe shaken / stirred recipe stirred");
            sb.AppendLine("            (a pint instead scores its HEAD, and nothing else)");
            sb.AppendLine("```");
            sb.AppendLine();
            sb.AppendLine("So a perfect serve **doubles** the take and a careless one keeps only the");
            sb.AppendLine("base — the money is in the service, not the pour.");
            sb.AppendLine();
            sb.AppendLine("| hard rule | where | what it does |");
            sb.AppendLine("|---|---|---|");
            sb.AppendLine($"| glass under {P(ServiceJudge.RefusalFill)} full | `ServiceJudge.RefusalFill` "
                          + "| refused outright — **$0**, no tip, satisfaction 0.02 |");
            sb.AppendLine("| glass under the recipe's own `MinFill` | `RatioRecipe.Satisfies` "
                          + "| the drink does not match the recipe **at all** |");
            sb.AppendLine("| broke crowd | `BarRating.BrokeStars = " + F(BarRating.BrokeStars) + "` "
                          + "| never tips, whatever the serve |");
            sb.AppendLine("| wrong drink | `ServiceJudge.Judge` | never tips |");
            sb.AppendLine($"| more than {P(RatioRecipeMatcher.MaxUnnamedShare)} of the glass unnamed "
                          + "| `RatioRecipe.Satisfies` | a different drink wearing the proportions |");
            sb.AppendLine();
        }

        private static void Drinks(StringBuilder sb, IReadOnlyList<RecipeDefinition> recipes,
            IReadOnlyList<GlasswareDefinition> glassware)
        {
            sb.AppendLine("## The menu");
            sb.AppendLine();
            sb.AppendLine("Base price is `3 + (rank + 1) / 2` (`DrinkOrder.MenuPrice`), so the ladder is");
            sb.AppendLine("deliberately shallow: rank 1 pays $4 and rank 28 pays $17. **Best** is a");
            sb.AppendLine("perfect serve — base doubled. **Method graded** marks the drinks where");
            sb.AppendLine("shaking or stirring is worth "
                          + P(ServiceJudge.SpecWeight * ServiceJudge.MethodShare)
                          + " of the tip; on the rest the method is scored 1.0 whatever you do.");
            sb.AppendLine();
            sb.AppendLine("| drink | rank | glass | base | best | method graded | the pour |");
            sb.AppendLine("|---|---:|---|---:|---:|:---:|---|");

            var sorted = new List<RecipeDefinition>(recipes);
            sorted.Sort((a, b) => a.Rank != b.Rank
                ? a.Rank.CompareTo(b.Rank)
                : string.CompareOrdinal(a.Name, b.Name));

            foreach (var r in sorted)
            {
                if (r.RatioRequirements.Count == 0) continue;   // not pourable: never ordered
                int price = DrinkOrder.MenuPrice(r);
                bool graded = r.Prep == PrepMethod.Shaken || r.Prep == PrepMethod.Stirred;
                sb.AppendLine($"| {r.Name} | {r.Rank} | {Glass(r, glassware)} | ${price} "
                              + $"| ${price * 2} | {(graded ? r.Prep.ToString().ToUpperInvariant() : "—")} "
                              + $"| {Pour(r)} |");
            }
            sb.AppendLine();
        }

        private static void Craft(StringBuilder sb, LoadedDeck deck)
        {
            sb.AppendLine("## What a garnish is worth");
            sb.AppendLine();
            sb.AppendLine("A customer's asks are **all-or-nothing each**: `ServingSpec.Delivered`");
            sb.AppendLine("returns the SHARE of them that landed, so on an order with two asks each one");
            sb.AppendLine("is half the ask score. The ask score is "
                          + P(ServiceJudge.GarnishShare) + " of craft, and craft is "
                          + P(ServiceJudge.SpecWeight) + " of the tip:");
            sb.AppendLine();
            sb.AppendLine("```");
            sb.AppendLine("  one ask, on a one-ask order = "
                          + P(ServiceJudge.SpecWeight * ServiceJudge.GarnishShare)
                          + " of the tip  = " + P(ServiceJudge.SpecWeight * ServiceJudge.GarnishShare
                                                  * ServiceJudge.TipCeiling) + " of the base price");
            sb.AppendLine("  on a $6 drink that is $" + (6 * ServiceJudge.TipCeiling
                          * ServiceJudge.SpecWeight * ServiceJudge.GarnishShare)
                          .ToString("0.00", Inv) + " — for one twist");
            sb.AppendLine("```");
            sb.AppendLine();
            sb.AppendLine("Missing every ask on a two-ask order therefore costs about a fifth of the");
            sb.AppendLine("tip, and it also kills the **extra round**: `craftForExtra` needs the spec");
            sb.AppendLine("delivered whole AND the method right, so a plain drink poured plainly can");
            sb.AppendLine("never earn one — a customer who asked for nothing has not been read.");
            sb.AppendLine();
            sb.AppendLine("What they can ask for, and what it costs you to hold it:");
            sb.AppendLine();
            sb.AppendLine("| ask | shelf price | restock | notes |");
            sb.AppendLine("|---|---:|---:|---|");
            foreach (var card in deck.Cards)
            {
                if (card.Type != IngredientType.Garnish) continue;
                sb.AppendLine($"| {card.Name} | {Money(card.Info?.Price ?? 0)} "
                              + $"| {Money(RefillOf(card))} | garnish |");
            }
            sb.AppendLine();
            sb.AppendLine("Ice and the rims are free of the shelf entirely — they are preparations, not");
            sb.AppendLine("stock, so they cost only the seconds spent adding them.");
            sb.AppendLine();
            sb.AppendLine("The **method** is not on this list on purpose (2026-08-11): how a drink is");
            sb.AppendLine("worked belongs to the book, not to the customer. It is graded against the");
            sb.AppendLine("ORDERED recipe's own `Prep` — a Martini wants stirring whoever ordered it —");
            sb.AppendLine("and it is worth " + P(ServiceJudge.SpecWeight * ServiceJudge.MethodShare)
                          + " of the tip on every shaken or stirred drink, all or nothing.");
            sb.AppendLine("Built recipes are the \"either, or neither\" class and always score 1.0.");
            sb.AppendLine();
        }

        private static void Stars(StringBuilder sb)
        {
            sb.AppendLine("## Stars");
            sb.AppendLine();
            sb.AppendLine("One visit's satisfaction (`ServiceJudge.Judge`):");
            sb.AppendLine();
            sb.AppendLine("```");
            sb.AppendLine("  exact drink        +0.75      close (right family)  +0.50");
            sb.AppendLine("  wrong drink        +0.05      declined              0.15 flat");
            sb.AppendLine("  craft              +0.20 × (craft − 0.5)");
            sb.AppendLine("  fill               +0.12 × (fill  − 0.5)");
            sb.AppendLine("  waiting            −0.30 × how much of their patience was spent");
            sb.AppendLine("  + the room's ambience bonus");
            sb.AppendLine("```");
            sb.AppendLine();
            sb.AppendLine("Satisfaction becomes stars linearly — `1 + 4 × satisfaction`, so **zero");
            sb.AppendLine("satisfaction is one star, not none**; the scale starts at one and somebody");
            sb.AppendLine("who storms off still fills in the card.");
            sb.AppendLine();
            sb.AppendLine("| satisfaction | stars |");
            sb.AppendLine("|---:|---:|");
            foreach (double s in new[] { 0.0, 0.25, 0.5, 0.75, 1.0 })
                sb.AppendLine($"| {F(s)} | {BarRating.ExactStarsFor(s).ToString("0.0", Inv)} |");
            sb.AppendLine();
            sb.AppendLine("The **standing** — the number in the top corner — is inertial. A night's");
            sb.AppendLine("average is capped by what the fittings and the menu allow, then the standing");
            sb.AppendLine("takes one step toward it:");
            sb.AppendLine();
            sb.AppendLine($"- climbing: {P(BarRating.GainRate)} of the gap, at most "
                          + $"**+{F(BarRating.MaxNightlyGain)} a night**");
            sb.AppendLine($"- falling: {P(BarRating.LossRate)} of the gap — twice as fast, and uncapped");
            sb.AppendLine($"- start: {F(BarRating.StartStars)}; the climb is the game");
            sb.AppendLine();
            sb.AppendLine("So a single five-star night cannot buy a reputation, and a single dreadful");
            sb.AppendLine("one costs double what it would have earned. What the standing then buys:");
            sb.AppendLine();
            sb.AppendLine($"- **{F(BarRating.HighRollerStars)}+** — high rollers start coming in");
            sb.AppendLine($"- **under {F(BarRating.BrokeStars)} last night** — tomorrow's crowd is broke "
                          + "and tips **nothing**");
            sb.AppendLine($"- arrivals pivot around {F(BarRating.ArrivalPivot)}, not the display "
                          + "middle of " + F(BarRating.NeutralStars));
            sb.AppendLine();
        }

        private static void Shelf(StringBuilder sb, LoadedDeck deck, TycoonConfig config)
        {
            sb.AppendLine("## The shelf");
            sb.AppendLine();
            sb.AppendLine($"A bottle holds **{F(ShelfBottle.BottleCapacity)} glasses** and a keg holds "
                          + $"**{F(ShelfBottle.KegCapacity)}**. Refilling costs "
                          + $"**${config.RefillPricePerCapacity} per glass of capacity**, plus "
                          + $"**${config.StockPremiumPerTier} per tier above the well** — so what a");
            sb.AppendLine("bottle costs to *keep* is usually the number that matters, not what it cost");
            sb.AppendLine("to buy. `cost/pour` is that refill spread over the bottle.");
            sb.AppendLine();
            sb.AppendLine("| bottle | style | tier | buy | refill | cost/pour |");
            sb.AppendLine("|---|---|---:|---:|---:|---:|");
            foreach (var card in deck.Cards)
            {
                if (card.Type == IngredientType.Garnish) continue;
                double cap = card.Type == IngredientType.Beer
                    ? ShelfBottle.KegCapacity : ShelfBottle.BottleCapacity;
                int refill = RefillOf(card);
                sb.AppendLine($"| {card.Name} | {card.Info?.Style ?? "—"} | {card.Info?.Tier ?? 1} "
                              + $"| {Money(card.Info?.Price ?? 0)} | {Money(refill)} "
                              + $"| ${(refill / cap).ToString("0.00", Inv)} |");
            }
            sb.AppendLine();
            sb.AppendLine("Read the last column against the menu table: a drink whose cost per pour");
            sb.AppendLine("approaches its base price is one the bar loses money serving carelessly, and");
            sb.AppendLine("earns on only when the tip lands.");
            sb.AppendLine();
        }

        private static void Night(StringBuilder sb, TycoonConfig config)
        {
            sb.AppendLine("## The night");
            sb.AppendLine();
            sb.AppendLine($"- starting money **${config.StartingMoney}**, "
                          + $"{config.StartingSeats} seats (max {config.MaxSeats})");
            sb.AppendLine($"- a night runs **{F(config.NightSeconds)} seconds**");
            sb.AppendLine($"- a customer balks if **{config.BalkAtWaiting}** are already waiting");
            sb.AppendLine($"- at most **{config.MaxUpgradesPerNight}** upgrade a night");
            sb.AppendLine();
            sb.AppendLine("Rent is `12 + 2·day + day²/9`, which is the pressure the whole loop runs");
            sb.AppendLine("against — it rises faster than linearly, so a bar that stops improving");
            sb.AppendLine("eventually cannot pay:");
            sb.AppendLine();
            sb.AppendLine("| day | 1 | 3 | 5 | 7 | 10 | 14 | 21 |");
            sb.AppendLine("|---|---:|---:|---:|---:|---:|---:|---:|");
            sb.Append("| rent |");
            foreach (int d in new[] { 1, 3, 5, 7, 10, 14, 21 }) sb.Append($" ${config.Rent(d)} |");
            sb.AppendLine();
            sb.AppendLine();
        }

        private static void Footer(StringBuilder sb)
        {
            sb.AppendLine("---");
            sb.AppendLine();
            sb.AppendLine("Every figure above comes from: `DrinkOrder.MenuPrice`, `ServiceJudge`,");
            sb.AppendLine("`ServingSpec`, `BarRating`, `RatioRecipe`, `ShelfBottle`, `TycoonConfig`,");
            sb.AppendLine("and the JSON under `Assets/Data`. Nothing here is typed in by hand.");
            sb.AppendLine();
        }

        // ── small helpers ───────────────────────────────────────────────────────

        private static int RefillOf(IngredientCard card)
        {
            double cap = card.Type == IngredientType.Beer
                ? ShelfBottle.KegCapacity : ShelfBottle.BottleCapacity;
            int tier = card.Info?.Tier ?? 1;
            var config = new TycoonConfig();
            return (int)System.Math.Ceiling(cap * config.RefillPricePerCapacity)
                   + config.StockPremiumPerTier * (tier - 1);
        }

        private static string Glass(RecipeDefinition r, IReadOnlyList<GlasswareDefinition> all)
        {
            if (string.IsNullOrEmpty(r.GlassId)) return "—";
            foreach (var g in all) if (g.Id == r.GlassId) return g.Name;
            return r.GlassId;
        }

        /// <summary>The pour as the cards print it: the exact shares, not the tolerance bands —
        /// the same reading <c>RatioRecipeMatcher.IdealPour</c> gives the licence and the book.</summary>
        private static string Pour(RecipeDefinition r)
        {
            var shares = RatioRecipeMatcher.IdealPour(r);
            var parts = new List<string>();
            for (int i = 0; i < r.RatioRequirements.Count; i++)
            {
                var b = r.RatioRequirements[i];
                string who = b.IsStyleBand
                    ? b.Style.Replace('_', ' ').ToUpperInvariant()
                    : "any " + b.Type.ToString().ToLowerInvariant();
                if (b.MinTier > 1) who += $" (tier {b.MinTier}+)";
                parts.Add($"{who} {(shares[i] * 100).ToString("0", Inv)}%");
            }
            if (r.MinFill > 0) parts.Add($"fill {P(r.MinFill)}+");
            return string.Join(" · ", parts);
        }

        private static string Money(int v) => v > 0 ? "$" + v.ToString(Inv) : "—";
        private static string F(double v) => v.ToString("0.##", Inv);
        private static string P(double v) => (v * 100).ToString("0", Inv) + "%";
    }
}
