"""Checks and merges the L1 string-table fragments into Assets/Resources/Data/loc/en.json.

Localization L1 (Docs/PLAN_localization_L1.md section 7). Each worker writes
Tools/loc/fragments/<group>.json = {"group": "<group>", "strings": [{"key", "text", "note"}]};
data_keys.py writes fragments/data.json. This applies the rules StringTable enforces when the game
loads the table (Assets/Scripts/Core/Text/StringTable.cs), so a bad line fails here instead of on
screen.

    py -3 -X utf8 Tools/loc/merge_fragments.py            same as --check
    py -3 -X utf8 Tools/loc/merge_fragments.py --check    report per group; exit 1 on any error
    py -3 -X utf8 Tools/loc/merge_fragments.py --write    --check, then write en.json if it passed
    py -3 -X utf8 Tools/loc/merge_fragments.py --stale tr keys of tr.json whose src != current English

--update (with --check or --write): a fragment whose text differs from en.json replaces it (reported
as CHANGED) instead of being an error; for a data file edit re-generated by data_keys.py. Two
fragments that disagree are always an error.

Standard library only.
"""

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LOC = ROOT / "Assets" / "Resources" / "Data" / "loc"
EN = LOC / "en.json"
FRAGMENTS = ROOT / "Tools" / "loc" / "fragments"

PLURAL_SUFFIXES = ("zero", "one", "two", "few", "many", "other")
CONVENTION = re.compile(r"^[a-z0-9_]+(\.[a-z0-9_]+)+(#(zero|one|two|few|many|other))?$")
EN_GROUP = "en.json"


# ---- the rules StringTable enforces -------------------------------------------------------------

def key_problem(key):
    """Port of StringTable's key checks, or None."""
    if not isinstance(key, str) or not key.strip():
        return "empty key"
    if any(c.isspace() for c in key):
        return "key has a space in it"
    mark = key.find("#")
    if mark >= 0 and (mark == 0 or key[mark + 1:] not in PLURAL_SUFFIXES):
        return "after '#' comes one of zero, one, two, few, many, other"
    return None


def placeholder_problem(text):
    """Port of StringTable.PlaceholderProblem."""
    depth, start = 0, 0
    for i, c in enumerate(text):
        if c == "{":
            if depth > 0:
                return "a '{' opens inside another placeholder"
            depth, start = 1, i + 1
        elif c == "}":
            if depth == 0:
                return "a '}' closes nothing"
            depth = 0
            name = text[start:i]
            if not name:
                return "an empty placeholder '{}'"
            if any(not (("a" <= n <= "z") or ("0" <= n <= "9") or n == "_") for n in name):
                return f"placeholder '{{{name}}}' is not lower_snake_case"
    return "a '{' never closes" if depth > 0 else None


def base_key(key):
    mark = key.find("#")
    return key if mark < 0 else key[:mark]


def placeholders(text):
    return set(re.findall(r"\{([^{}]*)\}", text))


# ---- loading ------------------------------------------------------------------------------------

class Group:
    def __init__(self, name, path):
        self.name = name
        self.path = path
        self.entries = []        # well-formed entry dicts, in file order
        self.fatal = None        # the file could not be used at all
        self.errors = []
        self.warnings = []
        self.info = []
        self.new_keys = 0
        self.dup_same = 0
        self.dup_diff = 0
        self.changed = 0
        self.key_errors = 0
        self.placeholder_errors = 0
        self.plural_missing = 0
        self.no_note = 0


def read_json(path):
    with open(path, encoding="utf-8-sig") as f:
        return json.load(f)


def load_group(name, path, expect_code=None):
    g = Group(name, path)
    rel = path.relative_to(ROOT).as_posix()
    try:
        doc = read_json(path)
    except OSError as e:
        g.fatal = f"{rel}: cannot open ({e})"
        return g
    except json.JSONDecodeError as e:
        g.fatal = f"{rel}: not valid JSON, line {e.lineno} col {e.colno}: {e.msg} (half-written?)"
        return g
    if not isinstance(doc, dict):
        g.fatal = f"{rel}: top level is not an object"
        return g
    if expect_code is not None:
        if doc.get("code") != expect_code:
            g.fatal = f"{rel}: code is {doc.get('code')!r}, expected {expect_code!r}"
            return g
    else:
        declared = doc.get("group")
        if declared != name:
            g.warnings.append(f"declares group {declared!r}, file is named {name!r}")
    strings = doc.get("strings")
    if not isinstance(strings, list):
        g.fatal = f"{rel}: no 'strings' list"
        return g
    if not strings:
        g.warnings.append("'strings' is empty")
    for i, s in enumerate(strings):
        if not isinstance(s, dict):
            g.errors.append(f"strings[{i}] is not an object")
            continue
        key, text = s.get("key"), s.get("text")
        if not isinstance(key, str):
            g.errors.append(f"strings[{i}] has no string 'key' ({key!r})")
            g.key_errors += 1
            continue
        if not isinstance(text, str):
            g.errors.append(f"{key}: no text ({text!r})")
            continue
        g.entries.append(s)
    return g


# ---- the check ----------------------------------------------------------------------------------

def check(update):
    """Returns (groups, merged, ok). merged: key -> (entry, owning group name)."""
    en = load_group(EN_GROUP, EN, expect_code="en")
    groups = [en]
    if FRAGMENTS.is_dir():
        for path in sorted(FRAGMENTS.glob("*.json")):
            groups.append(load_group(path.stem, path))

    en_keys = {}
    if en.fatal is None:
        for s in en.entries:
            en_keys.setdefault(s["key"], s)

    merged = {}   # key -> (entry, group name)
    for g in groups:
        if g.fatal is not None:
            continue
        seen_here = {}
        for s in g.entries:
            key, text = s["key"], s["text"]
            problem = key_problem(key)
            if problem:
                g.errors.append(f"{key!r}: {problem}")
                g.key_errors += 1
                continue
            if not CONVENTION.match(key):
                g.warnings.append(f"{key}: not area.element lower_snake ASCII (plan section 2)")
            problem = placeholder_problem(text)
            if problem:
                g.errors.append(f"{key}: {problem} (text {text!r})")
                g.placeholder_errors += 1
            note = s.get("note")
            if not isinstance(note, str) or not note.strip():
                g.errors.append(f"{key}: no note")
                g.no_note += 1
            if text == "":
                g.warnings.append(f"{key}: empty text")

            if key in seen_here:
                if seen_here[key] == text:
                    g.dup_same += 1
                    g.info.append(f"{key}: listed twice in this group with the same text (merged)")
                else:
                    g.dup_diff += 1
                    g.errors.append(f"{key}: listed twice in this group with different texts: "
                                    f"{seen_here[key]!r} vs {text!r}")
                continue
            seen_here[key] = text

            if g.name != EN_GROUP and key not in en_keys:
                g.new_keys += 1
            if key not in merged:
                merged[key] = (s, g.name)
                continue
            other, owner = merged[key]
            if other["text"] == text:
                g.dup_same += 1
                if owner != EN_GROUP:  # already in en.json is the normal re-run case; the count says it
                    g.info.append(f"{key}: also in {owner}, same text (merged)")
            elif owner == EN_GROUP and update:
                g.changed += 1
                g.info.append(f"{key}: CHANGED from en.json {other['text']!r} to {text!r} (--update)")
                merged[key] = (s, g.name)
            else:
                g.dup_diff += 1
                where = f"{owner} has {other['text']!r}, {g.name} has {text!r}"
                g.errors.append(f"{key}: different text in two groups: {where}")
                if owner != EN_GROUP:
                    owning = next(x for x in groups if x.name == owner)
                    owning.dup_diff += 1
                    owning.errors.append(f"{key}: different text in two groups: {where}")

    # counted keys need their #one and #other partners somewhere in the merged table
    variants = {}
    for key, (entry, owner) in merged.items():
        if "#" in key:
            variants.setdefault(base_key(key), {})[key[key.find("#") + 1:]] = (entry, owner)
    by_name = {g.name: g for g in groups}
    for base in sorted(variants):
        present = variants[base]
        missing = [sfx for sfx in ("one", "other") if sfx not in present]
        owners = sorted({owner for _, owner in present.values()})
        for owner in owners:
            g = by_name[owner]
            if missing:
                g.plural_missing += 1
                g.errors.append(f"{base}: counted key without " + " and ".join(f"#{m}" for m in missing))
        if base in merged:
            for owner in owners:
                by_name[owner].warnings.append(f"{base}: exists both plain and counted")
        sets = {sfx: placeholders(e["text"]) for sfx, (e, _) in present.items()}
        if "other" in sets:
            for sfx, names in sets.items():
                extra = names - sets["other"]
                if extra:
                    by_name[present[sfx][1]].warnings.append(
                        f"{base}#{sfx}: slots {sorted(extra)} not in #other")

    ok = all(g.fatal is None and not g.errors for g in groups)
    return groups, merged, ok


def print_report(groups, merged, ok, update):
    print(f"en.json + {len(groups) - 1} fragment file(s) in {FRAGMENTS.relative_to(ROOT).as_posix()}/")
    if len(groups) == 1:
        print("  (no fragments yet)")
    print()
    head = f"{'group':<14} {'entries':>7} {'new':>5} {'dup=':>5} {'dup!=':>5} {'keys!':>5} {'{}!':>4} {'#!':>3} {'note!':>5}"
    if update:
        head += f" {'chg':>4}"
    print(head)
    for g in groups:
        if g.fatal is not None:
            print(f"{g.name:<14} UNUSABLE")
            continue
        row = (f"{g.name:<14} {len(g.entries):>7} {g.new_keys if g.name != EN_GROUP else '-':>5} "
               f"{g.dup_same:>5} {g.dup_diff:>5} {g.key_errors:>5} {g.placeholder_errors:>4} "
               f"{g.plural_missing:>3} {g.no_note:>5}")
        if update:
            row += f" {g.changed:>4}"
        print(row)
    print()
    print("new = not in en.json yet; dup= same key same text (merged); dup!= same key, different text;")
    print("keys! key-rule violations; {}! placeholder syntax; #! counted key missing #one/#other; note! no note")

    for g in groups:
        if g.fatal is None and not (g.errors or g.warnings or g.info):
            continue
        print()
        print(f"--- {g.name}")
        if g.fatal is not None:
            print(f"  ERROR {g.fatal}")
            continue
        for e in g.errors:
            print(f"  ERROR {e}")
        for w in g.warnings:
            print(f"  warn  {w}")
        for i in g.info:
            print(f"  info  {i}")

    print()
    errors = sum((1 if g.fatal else 0) + len(g.errors) for g in groups)
    print(f"merged table: {len(merged)} keys")
    print("CHECK PASSED" if ok else f"CHECK FAILED: {errors} error(s)")


# ---- write --------------------------------------------------------------------------------------

def render_table(entries):
    lines = ["{", '  "code": "en",', '  "strings": [']
    for i, s in enumerate(entries):
        fields = [("key", s["key"]), ("text", s["text"])]
        for extra in ("note", "src"):
            if isinstance(s.get(extra), str):
                fields.append((extra, s[extra]))
        body = ", ".join(f"{json.dumps(k)}: {json.dumps(v, ensure_ascii=False)}" for k, v in fields)
        lines.append("    { " + body + " }" + ("," if i < len(entries) - 1 else ""))
    lines += ["  ]", "}"]
    return "\n".join(lines) + "\n"


def merged_entries(merged):
    out = []
    for key in sorted(merged):
        entry, owner = merged[key]
        row = {"key": key, "text": entry["text"]}
        if isinstance(entry.get("note"), str):
            row["note"] = entry["note"]
        if owner == EN_GROUP and isinstance(entry.get("src"), str):
            row["src"] = entry["src"]
        out.append(row)
    return out


def write(merged):
    content = render_table(merged_entries(merged))
    old = EN.read_bytes()
    newline = "\r\n" if b"\r\n" in old else "\n"
    data = content.replace("\n", newline).encode("utf-8")
    if data == old:
        print(f"{EN.relative_to(ROOT).as_posix()} unchanged")
        return
    EN.write_bytes(data)
    print(f"wrote {EN.relative_to(ROOT).as_posix()}: {len(merged)} keys")


# ---- stale --------------------------------------------------------------------------------------

def stale(code):
    path = LOC / f"{code}.json"
    en = load_group(EN_GROUP, EN, expect_code="en")
    tr = load_group(code, path, expect_code=code)
    for g in (en, tr):
        if g.fatal is not None:
            print(f"ERROR {g.fatal}")
            return 1
    english = {}
    for s in en.entries:
        english.setdefault(s["key"], s["text"])
    stale_rows, orphans, seen = [], [], set()
    for s in tr.entries:
        key = s["key"]
        seen.add(key)
        if key not in english:
            orphans.append(key)
            continue
        src = s.get("src")
        if src != english[key]:
            stale_rows.append((key, src, english[key]))
    missing = sorted(k for k in english if k not in seen)

    rel = path.relative_to(ROOT).as_posix()
    print(f"{rel}: {len(tr.entries)} entries against {len(english)} English keys")
    print()
    print(f"STALE ({len(stale_rows)}): src differs from the current English")
    for key, src, now in sorted(stale_rows):
        was = "no src" if src is None else repr(src)
        print(f"  {key}\n      src: {was}\n      now: {now!r}")
    print(f"ORPHANS ({len(orphans)}): keys en.json no longer has")
    for key in sorted(orphans):
        print(f"  {key}")
    print(f"UNTRANSLATED: {len(missing)} English key(s) not in {code}.json")
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="report only (default)")
    mode.add_argument("--write", action="store_true", help="check, then write en.json if it passed")
    mode.add_argument("--stale", metavar="CODE", help="list keys of <CODE>.json whose src != English")
    parser.add_argument("--update", action="store_true",
                        help="a fragment text differing from en.json replaces it instead of erroring")
    args = parser.parse_args()

    if args.stale:
        return stale(args.stale)
    groups, merged, ok = check(args.update)
    print_report(groups, merged, ok, args.update)
    if not ok:
        if args.write:
            print("en.json NOT written.")
        return 1
    if args.write:
        write(merged)
    return 0


if __name__ == "__main__":
    sys.exit(main())
