# -*- coding: utf-8 -*-
"""A customer drawn in an APPROVED customer's hand (2026-08-20).

WHY THIS EXISTS. The cast has been generated by describing the line language in words -
"lineless", "no black outline", "no dark keyline" - and on 2026-08-19 that worked: six
faces came back clean on a single generation each. On 2026-08-20 it stopped working. Four
strategies were tried on one figure and every one of them came back inked:

    A  the brief as it stands (the clause that forbids the keyline)    19 / 93 / 98 %
    B  that clause removed entirely                                    91 / 91 / 39 %
    C  detail dropped to 'low' (the dial that fixed this in August)    91 / 95 / 84 %
    D  the contour described rather than banned, guidance raised to 12       77 %

Nineteen rolls, one usable drawing. The `outline` parameter is cleared by the cast's own
table - 'lineless' sits at 4% and at 98% - and the tool's schema says why the words are
so weak: in v3 mode `shading` is IGNORED outright and `outline` and `detail` are "soft
guidance". So the drawing's line language is not something the v3 character endpoint can
be TOLD; on a good day it agrees and on a bad day it does not.

WHAT THIS DOES INSTEAD. create_image_pro takes a style image and a `style_copy` list -
"which aspects to take from it: color_palette, outline, detail, shading". So the house
stops describing its line language and starts HANDING IT OVER: heavyset's own south
sprite goes in as the style, with color_palette deliberately LEFT OUT of style_copy so
the new person keeps their own clothes and their own skin. The author's brief for this
round was "trial heavyset gibi natural kontrasli", and this is that sentence executed
literally rather than paraphrased into a prompt.

heavyset is the reference and not a matter of taste: at 5% measured keyline he is the
cleanest drawing the casting has ever produced, against a cast that runs to 88%.

TWO STEPS, because the two halves of a character come from different endpoints:

    still <name>    create_image_pro, styled off heavyset -> one south-facing 220px
                    drawing, measured by the same gate every other face passes
    rotate <name>   create_character in v3 mode with that drawing as
                    reference_image_base64 - "rotates this exact sprite into 8
                    directions" - so the rig gets its turnaround without redrawing the
                    person and without re-entering the lottery

Cost, stated plainly because it is higher per face than the old road: a pro call is
20-40 generations against create_character's 7. It buys one drawing instead of three
rolls and a coin toss, so it is cheaper than the way this round actually went.
"""
import base64
import io
import json
import os
import re
import sys
import time

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import patron_prompts as brief          # noqa: E402
import patron_trial_gen as trial        # noqa: E402

RAW = trial.RAW
STATE = os.path.join(HERE, 'patron_style_state.json')

# The drawing whose hand the cast is now drawn in. Measured, not chosen: 5% keyline,
# 37 colours, 197px of body - and the author's own reference for this round.
STYLE_SLUG = 'heavyset'
# COLOUR IS NOT COPIED. The other three are exactly what the words could not carry, and
# the palette is the one thing each new customer must own - a cast in heavyset's cream
# and teal is one man drawn nine times.
STYLE_COPY = ['outline', 'detail', 'shading']


def load():
    return json.load(io.open(STATE, encoding='utf-8')) if os.path.exists(STATE) else {}


def save(s):
    io.open(STATE, 'w', encoding='utf-8').write(json.dumps(s, indent=1))


def style_b64():
    p = os.path.join(RAW, STYLE_SLUG + '.png')
    if not os.path.exists(p):
        raise SystemExit('no style sprite at ' + p)
    return base64.b64encode(io.open(p, 'rb').read()).decode()


def figure_text(name):
    """The person, and the pose - and NOT a word about lines.

    The house rules still come along (no baked light, adult proportions, transparent
    background), minus the paragraph that argues with the keyline: that argument is now
    made by the style image, and leaving the words in would have the two disagree.
    """
    keep = brief.HOUSE_RULES
    for clause in (
        "absolutely no black outline and no dark keyline, not around the figure and not "
        "around any garment, no ink lines, no drawn seams, no dark piping, no black edges; "
        "every edge is shown by a change of colour alone, ",
    ):
        keep = keep.replace(clause, "")
    return "%s, %s, %s" % (brief.FIGURE_OPTIONS[name], brief.NEUTRAL_POSE, keep)


def still(name, seed=None):
    """One styled south-facing drawing. One call, one candidate at this canvas size."""
    state = load()
    if state.get(name, {}).get('job_id') and not state[name].get('png'):
        print('  %-12s already queued (%s)' % (name, state[name]['job_id']))
        return
    args = {
        'description': figure_text(name),
        'width': brief.PIVOT_CANVAS_PX, 'height': brief.PIVOT_CANVAS_PX,
        'no_background': True,
        'style_image_base64': style_b64(),
        'style_copy': STYLE_COPY,
    }
    if seed is not None:
        args['seed'] = int(seed)
    text, images = trial.call('create_image_pro', args)
    job = None
    # The answer says "id: <uuid>", not "job_id" - the first UUID in it is the job.
    m = re.search(r'[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}', text, re.I)
    if m:
        job = m.group(0)
    entry = state.setdefault(name, {})
    entry.update({'job_id': job, 'style': STYLE_SLUG, 'style_copy': STYLE_COPY})
    save(state)
    if images:
        _keep(name, images[0])
    else:
        print('  %-12s queued %s' % (name, job or text.strip()[:160]))


def _keep(name, im):
    p = os.path.join(RAW, name + '__styled.png')
    im.save(p)
    state = load()
    st = trial.figure_stats(im) or {}
    state[name]['png'] = os.path.relpath(p, HERE)
    state[name]['measured'] = {k: (round(v, 3) if isinstance(v, float) else v)
                               for k, v in st.items()}
    save(state)
    trial.judge(name + ' (styled)', im)
    trial.log({'asset': 'patron_style/' + name, 'event': 'still',
               'style': STYLE_SLUG, 'style_copy': STYLE_COPY, 'measured': state[name]['measured']})


def poll(names=None):
    state = load()
    for name in (names or sorted(state)):
        e = state.get(name) or {}
        if e.get('png') or not e.get('job_id'):
            continue
        text, images = trial.call('get_image', {'job_id': e['job_id']})
        if not images:
            print('  %-12s %s' % (name, (text.strip().splitlines() or ['(silent)'])[0][:120]))
            continue
        _keep(name, images[0])


def rotate(name):
    """The styled drawing becomes a character: v3 rotates THIS sprite into 8 directions."""
    state = load()
    p = os.path.join(RAW, name + '__styled.png')
    if not os.path.exists(p):
        raise SystemExit('no styled still for ' + name + '; run: still ' + name)
    text, _ = trial.call('create_character', {
        'description': brief.FIGURE_OPTIONS[name],
        'name': 'styled %s' % name,
        'mode': 'v3',
        'reference_image_base64': base64.b64encode(io.open(p, 'rb').read()).decode(),
        'view': brief.PIVOT_VIEW,
    })
    m = re.search(r'[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}', text, re.I)
    if not m:
        print('  %-12s NO ID: %s' % (name, text[:200]))
        return
    state.setdefault(name, {})['character_id'] = m.group(0)
    save(state)
    trial.log({'asset': 'patron_style/' + name, 'event': 'rotated',
               'character_id': m.group(0)})
    print('  %-12s rotating as %s' % (name, m.group(0)))


if __name__ == '__main__':
    cmd = sys.argv[1] if len(sys.argv) > 1 else 'poll'
    if cmd == 'still':
        still(sys.argv[2], sys.argv[3] if len(sys.argv) > 3 else None)
    elif cmd == 'rotate':
        rotate(sys.argv[2])
    else:
        poll(sys.argv[2:] or None)
