# -*- coding: utf-8 -*-
"""The author's Nano Banana scene batch (2026-08-18) -> game-ready assets.

14 v3 SS11.E's post chain, run against the batch the author generated by hand:
crop -> area-downscale -> key -> quantize to the 55 -> binary alpha -> ship.

QUANTIZE IS OFF, on the author's call (2026-08-18: "quantize etme"). SS11.E's chain ends
in a snap to the 55 and this batch does not take it: the art is painted in its own muted
mauve-and-concrete range, and nearest-of-55 turns the parquet into speckle because the
floor's brown sits between Brick and Night with nothing in between. The step is kept
behind --quantize, palette still read from UITheme.cs (its one home, 14 v3 SS3, eleven
ramps of five asserted), so turning it back on is a flag and not a rewrite. What this
means downstream, said plainly: these assets are OFF-PALETTE by decision, so 14 SS3's
"every drawn pixel comes from here" now has a scene-art exception the bible should record.

SS11.B asks for flat #00FF00 panes and BANS a painted checkerboard. This batch shipped the
checkerboard anyway, so `key_checker` finds the panes by the pattern's own signature -- a
box where BOTH the white and the dusty pink appear is checker; a solid run of either is
paint, and paint stays. It is a rescue for one batch, not a licence: with a green key the
same job is one comparison.

The props arrive as SHEETS on white (two plants, three taps, two table arrangements per
tier), so `sheet` keys the white, splits on the empty columns between objects, and trims
each to its own alpha -- the same derive-don't-regenerate rule the bottles learned.

Commands:  measure [asset...]   report what the sources contain, ship nothing
           post    [asset...]   run the chain and write the assets
Sources:   %USERPROFILE%/Desktop/konsept art   (override with --src)
Log:       Tools/AssetPipeline/generation_log.jsonl (15 SS5)
"""
import io, json, os, sys, time

import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(os.path.expanduser('~'), 'Desktop', 'konsept art')
STAGE = os.path.join(HERE, 'AssetPipeline', 'staging', 'scene_nb')
LOG = os.path.join(HERE, 'AssetPipeline', 'generation_log.jsonl')
THEME = os.path.join(ROOT, 'Assets', 'Scripts', 'UI', 'UITheme.cs')

BACKGROUNDS = os.path.join(ROOT, 'Assets', 'Art', 'Backgrounds')
FIXTURES = os.path.join(ROOT, 'Assets', 'Resources', 'Fixtures')


# ── the palette, from its one home ──────────────────────────────────────────

def palette():
    """The 55 as (r,g,b), parsed out of UITheme.cs's eleven `Ramp(...)` ramps."""
    out = []
    with io.open(THEME, encoding='utf-8-sig') as f:
        for line in f:
            if '= Ramp(' not in line:
                continue
            body = line.split('= Ramp(', 1)[1].split(')', 1)[0]
            hexes = [p.strip() for p in body.split(',')]
            if len(hexes) != 5:                      # the type-colour map's single args
                continue
            for h in hexes:
                c = int(h, 16)
                out.append(((c >> 16) & 255, (c >> 8) & 255, c & 255))
    if len(out) != 55:
        raise SystemExit('UITheme.cs gave %d palette colours, expected 55 (11 ramps x 5). '
                         'The palette moved -- read 14 v3 SS3 before shipping.' % len(out))
    return np.array(out, dtype=np.int16)


PAL = None
QUANTIZE = False        # --quantize turns SS11.E's palette snap back on


def quantize(im):
    """Every opaque pixel to its nearest of the 55; anything under half alpha is cut.

    Nearest in plain RGB, the way scene_v3_gen quantized, so the two tools agree on what
    a colour becomes. Vectorised over the whole image at once -- the per-pixel cache in
    the older tool was fine for a 640-wide strip and hopeless on a 2752-wide master.
    """
    a = np.asarray(im.convert('RGBA'))
    rgb, alpha = a[:, :, :3], a[:, :, 3]
    # int32, NOT int16: a channel difference squares to 65025 and int16 tops out at 32767,
    # so the distance silently wraps negative and argmin picks a colour at random. It looked
    # like a palette that hated brown -- an espresso floor came back lime (2026-08-18).
    flat = rgb.reshape(-1, 3).astype(np.int32)
    pal = PAL.astype(np.int32)
    idx = np.empty(len(flat), dtype=np.int32)
    for i in range(0, len(flat), 200000):        # chunked: the full outer product on a
        blk = flat[i:i + 200000]                 # 2752-wide master is gigabytes
        idx[i:i + 200000] = ((blk[:, None, :] - pal[None, :, :]) ** 2).sum(2).argmin(1)
    q = PAL[idx].reshape(rgb.shape).astype(np.uint8)
    out = np.dstack([q, np.where(alpha >= 128, 255, 0).astype(np.uint8)])
    out[out[:, :, 3] == 0] = (0, 0, 0, 0)
    return Image.fromarray(out, 'RGBA')


def ship(im):
    """The last step before an asset is written: BINARY alpha, then the palette snap only
    if it was asked for.

    Binary alpha is not optional the way the snap is. Area-downscaling a keyed master
    averages the hole's zero with the frame's 255 and leaves a rim of half-transparent
    pixels; point-filtered at 1x in a pixel-perfect camera that rim reads as a dirty grey
    outline around every window and every stool leg.
    """
    a = np.asarray(im.convert('RGBA')).copy()
    a[:, :, 3] = np.where(a[:, :, 3] >= 128, 255, 0)
    a[a[:, :, 3] == 0] = (0, 0, 0, 0)
    im = Image.fromarray(a, 'RGBA')
    return quantize(im) if QUANTIZE else im


# ── masks ───────────────────────────────────────────────────────────────────

def boxmean(mask, k):
    """Mean of a binary mask over a (2k+1) square, by integral image (no scipy here)."""
    I = np.pad(mask.astype(np.int32), ((1, 0), (1, 0))).cumsum(0).cumsum(1)
    h, w = mask.shape
    ys, xs = np.arange(h), np.arange(w)
    y0, y1 = np.clip(ys - k, 0, h), np.clip(ys + k + 1, 0, h)
    x0, x1 = np.clip(xs - k, 0, w), np.clip(xs + k + 1, 0, w)
    s = (I[np.ix_(y1, x1)] - I[np.ix_(y0, x1)]
         - I[np.ix_(y1, x0)] + I[np.ix_(y0, x0)])
    return s / np.outer(y1 - y0, x1 - x0)


def key_checker(im):
    """Cut the painted checkerboard panes out of a room master (the SS11.B rescue).

    The checker alternates near-white with a dusty pink on a ~13px cell. Both colours also
    appear as PAINT elsewhere -- the ceiling is cream-white, the whole room carries a pink
    cast -- so neither colour alone can be keyed. What is unique to the panes is the two of
    them INTERLEAVED, so the test is a 21px box holding a real share of each. The closing
    radius is deliberately small: a wide close swallows the window's mullions, and SS7
    keeps the frame painted and keys only the glass.
    """
    a = np.asarray(im.convert('RGB')).astype(np.int16)
    r, g, b = a[:, :, 0], a[:, :, 1], a[:, :, 2]
    white = (r >= 238) & (g >= 238) & (b >= 238)
    pink = (abs(r - 214) <= 26) & (abs(g - 154) <= 26) & (abs(b - 153) <= 26)
    checker = (boxmean(white, 10) > 0.12) & (boxmean(pink, 10) > 0.12)
    mask = boxmean(checker, 6) > 0.45
    # A speck of false checker (a chrome highlight beside a pink pilaster) is dense over a
    # few px and sparse over forty; a pane is dense over both. Cheaper than labelling, and
    # the threshold is low enough that a pane's own corners survive.
    mask &= boxmean(mask, 20) > 0.25
    out = np.dstack([np.asarray(im.convert('RGB')), np.where(mask, 0, 255).astype(np.uint8)])
    return Image.fromarray(out, 'RGBA'), mask


def key_white(im, tol=8, min_run=3):
    """Cut a prop sheet's white ground -- including the ground ENCLOSED by a prop.

    Border-flooding alone is not enough and the table sheets are why: a bar table's legs and
    stretcher frame a rectangle of ground that no path from the edge reaches, so the first
    take shipped two tables with a white pane glazed into them.

    So background is defined by SIZE instead of reachability -- a white region wide enough to
    survive a morphological opening is ground, wherever it sits. A specular highlight on a
    steel leg is a few pixels across and erodes away; the pane under a tabletop is hundreds
    and does not. The one assumption is that no prop in the batch is itself large and white;
    a marble platform would need the reachability test back.
    """
    a = np.asarray(im.convert('RGB')).astype(np.int16)
    whiteish = ((a[:, :, 0] >= 255 - tol) & (a[:, :, 1] >= 255 - tol)
                & (a[:, :, 2] >= 255 - tol))
    core = boxmean(whiteish, min_run) > 0.98          # erode: only deep-inside white
    bg = whiteish & (boxmean(core, min_run + 2) > 0)  # dilate back, clipped to the white
    out = np.dstack([np.asarray(im.convert('RGB')), np.where(bg, 0, 255).astype(np.uint8)])
    return Image.fromarray(out, 'RGBA')


def flood_from_border(mask):
    """Everything in `mask` reachable (4-way) from the image border.

    PIL's flood fill does this in C. Growing the region with numpy dilation instead reaches
    one pixel per pass, which on a 3528-wide sheet is thousands of passes over ten million
    pixels -- correct, and slow enough to look broken.
    """
    from PIL import ImageDraw
    # .copy() IS LOAD-BEARING: Image.fromarray hands back an image sharing the numpy buffer,
    # which Pillow treats as read-only, and floodfill then writes nothing and raises nothing.
    # Without it the key silently no-ops and every sheet comes back as one opaque object.
    canvas = Image.fromarray(np.where(mask, 255, 0).astype(np.uint8), 'L').copy()
    h, w = mask.shape
    seeds = [(0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1)]
    for x, y in seeds:
        if canvas.getpixel((x, y)) == 255:
            ImageDraw.floodfill(canvas, (x, y), 128)
    return np.asarray(canvas) == 128


def alpha_bbox(im):
    a = np.asarray(im)[:, :, 3]
    ys, xs = np.where(a >= 128)
    if not len(xs):
        return None
    return int(xs.min()), int(ys.min()), int(xs.max()) + 1, int(ys.max()) + 1


def trim(im):
    box = alpha_bbox(im)
    return im.crop(box) if box else im


def fit_height(im, height):
    """Area-downscale to a target height, keeping aspect. Whole pixels out."""
    w = max(1, round(im.width * height / im.height))
    return im.resize((w, height), Image.BOX)


def split_sheet(im, count, gap_frac=0.01):
    """Split a keyed prop sheet into `count` objects on its empty columns."""
    a = np.asarray(im)[:, :, 3] >= 128
    cols = a.any(axis=0)
    runs, start = [], None
    for x, on in enumerate(cols):
        if on and start is None:
            start = x
        elif not on and start is not None:
            runs.append((start, x))
            start = None
    if start is not None:
        runs.append((start, len(cols)))
    # merge runs separated by less than gap_frac of the width (one object, two strokes)
    gap = max(2, int(im.width * gap_frac))
    merged = []
    for r in runs:
        if merged and r[0] - merged[-1][1] < gap:
            merged[-1] = (merged[-1][0], r[1])
        else:
            merged.append(r)
    merged.sort(key=lambda r: -(r[1] - r[0]))
    merged = sorted(merged[:count])
    return [trim(im.crop((x0, 0, x1, im.height))) for x0, x1 in merged]


def crop_aspect(im, aspect):
    """Centre-crop to an exact aspect ratio, losing the smaller axis' excess."""
    w, h = im.size
    if w / h > aspect:
        nw = int(round(h * aspect))
        off = (w - nw) // 2
        return im.crop((off, 0, off + nw, h))
    nh = int(round(w / aspect))
    off = (h - nh) // 2
    return im.crop((0, off, w, off + nh))


def top_of_content(im, dark_below=110):
    """First row from the top whose mean luminance leaves the baked-room band.

    The counter master carries a strip of the room above its back edge, which SS6 forbids
    outright ("no wall, no brick, no room"). The strip is dark and the slab under it is
    bright, so the boundary is the first row that is decisively brighter.
    """
    a = np.asarray(im.convert('RGB')).astype(float).mean(axis=2)
    rows = a.mean(axis=1)
    for y in range(len(rows)):
        if rows[y] > dark_below + 40:
            return y
    return 0


def src_file(fragment):
    """The one source file whose name contains `fragment`.

    Matched rather than spelled out: the batch's tap sheet is named in Turkish, and a
    literal 'fıçı' in this file survives exactly as long as nobody's editor guesses a
    codepage. A fragment that matches none or several is a naming change worth stopping on.
    """
    hits = [f for f in os.listdir(SRC) if fragment in f]
    if len(hits) != 1:
        raise SystemExit("'%s' matched %d files in %s: %s"
                         % (fragment, len(hits), SRC, hits))
    return os.path.join(SRC, hits[0])


def log(rec):
    rec['ts'] = time.strftime('%Y-%m-%dT%H:%M:%S')
    os.makedirs(os.path.dirname(LOG), exist_ok=True)
    with io.open(LOG, 'a', encoding='utf-8') as f:
        f.write(json.dumps(rec, ensure_ascii=False) + '\n')


def save(im, path, key):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    im.save(path)
    os.makedirs(STAGE, exist_ok=True)
    im.save(os.path.join(STAGE, os.path.basename(path)))
    print('  -> %-46s %dx%d' % (os.path.relpath(path, ROOT), im.width, im.height))
    log({'asset': key, 'event': 'posted', 'source_batch': 'nano-banana 2026-08-18',
         'path': os.path.relpath(path, ROOT), 'size': [im.width, im.height]})


# ── the recipes ─────────────────────────────────────────────────────────────

def post_room():
    im = Image.open(src_file('main room.'))
    keyed, mask = key_checker(im)
    print('  panes keyed: %d src px (%.1f%% of the master)'
          % (mask.sum(), 100.0 * mask.sum() / mask.size))
    keyed = crop_aspect(keyed, 16 / 9).resize((640, 360), Image.BOX)
    save(ship(keyed), os.path.join(BACKGROUNDS, 'club_room.png'), 'club_room')


def post_counter():
    im = Image.open(src_file('tezgah')).convert('RGB')
    cut = top_of_content(im)
    print('  baked-room strip cut: %d src rows off the top' % cut)
    im = im.crop((0, cut, im.width, im.height)).resize((640, 150), Image.BOX)
    save(ship(im), os.path.join(BACKGROUNDS, 'counter.png'), 'counter')


# Heights re-derived from the author's two layout references (2026-08-18, "tam olarak
# böyle"). The palm is the plant the room reference actually stands by the window and it
# is TALLER than the bar tables there -- 79 units against their 73 -- which the first pass
# had at 40, half a table high and reading as a desk plant.
PLANTS = [('fx_monstera', 46), ('fx_fern', 79)]
# The counter reference draws ONE tower, and its height is almost exactly the distance from
# the counter's top edge to the cabinet line (220 ref px against 225). That ratio is
# scale-free, which matters because the reference is a fuller scene than tezgah.jpg and the
# two cannot be compared pixel for pixel -- in this counter's 150 rows that distance is 70,
# so the tower is 69 and its own aspect gives the width.
TAPS = [('fx_tap_single', 62), ('fx_tap_triple', 69), ('fx_tap_double', 65)]
# Named by the author's own TIER, not by material: the sheets read lvl1 rustic-oak,
# lvl2 brass-and-green-leather, lvl3 steel-and-plum, and a first pass that named them for
# what they looked like had t2 and t3 swapped. The tier is what the market sells.
TABLES = {'lvl1_masa': ('fx_table_t1', 74),
          'lvl2_masa': ('fx_table_t2', 78),
          'lvl3_masa': ('fx_table_t3', 74)}


def post_sheet(src, targets, count):
    im = key_white(Image.open(src_file(src)))
    parts = split_sheet(im, count)
    print('  %s -> %d object(s): %s' % (src, len(parts), [p.size for p in parts]))
    for part, (name, height) in zip(parts, targets):
        save(ship(fit_height(part, height)),
             os.path.join(FIXTURES, name + '.png'), name)


def post_plants():
    post_sheet('bitki_1-2', PLANTS, 2)


def post_taps():
    post_sheet('_1-2-3', TAPS, 3)


def post_tables():
    for src, (name, height) in TABLES.items():
        im = key_white(Image.open(src_file(src)))
        parts = split_sheet(im, 2)          # the sheet draws the set twice; take the left
        print('  %s -> %d arrangement(s): %s' % (src, len(parts), [p.size for p in parts]))
        save(ship(fit_height(parts[0], height)),
             os.path.join(FIXTURES, name + '.png'), name)


# The sky the keyed panes look out on. Two tones and a 2x2 dither between them, in the
# ROOM's own light rather than the palette's -- the master is off-palette by the author's
# call, and a strictly-55 sky beside off-palette plaster would read as a sticker.
SKY_TOP, SKY_LOW = (0xF2, 0xE6, 0xD4), (0xD6, 0xA6, 0xA4)


def post_window():
    """The day window plate, cut to the room's OWN hole (14 v3 SS7's plate, this room's
    geometry).

    SS5b puts the window at x 234..407 dead centre; this room's runs down the LEFT wall in
    perspective, x 0..129 and y 58..234. So the plate is not authored to a nominal box at
    all -- it is the room master's alpha hole, filled. Derived that way it cannot drift out
    of register, and when the room is regenerated the plate follows for free.

    Shipped at the room's full 640x360 so the stage can draw it behind the shell through the
    very same cover fit, with no second set of measured constants to keep in step.
    """
    room = Image.open(os.path.join(BACKGROUNDS, 'club_room.png')).convert('RGBA')
    hole = np.asarray(room)[:, :, 3] < 128
    h, w = hole.shape
    ys = np.arange(h)[:, None].repeat(w, 1)
    rows = np.where(hole.any(1))[0]
    t = (ys - rows.min()) / max(1, rows.max() - rows.min())
    bayer = (np.indices((h, w)).sum(0) % 2) * 0.5      # 2x2 ordered dither, one step wide
    t = np.clip(t + (bayer - 0.25) * 0.14, 0, 1)
    out = np.zeros((h, w, 4), np.uint8)
    for c in range(3):
        out[:, :, c] = (SKY_TOP[c] + (SKY_LOW[c] - SKY_TOP[c]) * t).astype(np.uint8)
    out[:, :, 3] = np.where(hole, 255, 0)
    out[~hole] = (0, 0, 0, 0)
    print('  plate cut to the room hole: rows %d..%d' % (rows.min(), rows.max()))
    save(Image.fromarray(out, 'RGBA'),
         os.path.join(ROOT, 'Assets', 'Resources', 'Scene', 'window_day.png'), 'window_day')


def post_backbar():
    """SS6 keeps the back bar a DELIBERATE sitting: it is a LookTests-compared screen and
    BackBarArt lays its strips out in code, so the master art-directs and is sliced later.
    Staged at 640, never shipped from here."""
    im = Image.open(src_file('backbar2')).convert('RGBA')
    im = im.resize((640, round(640 * im.height / im.width)), Image.BOX)
    os.makedirs(STAGE, exist_ok=True)
    ship(im).save(os.path.join(STAGE, 'backbar.png'))
    print('  -> staged only (SS6): %s' % os.path.join('Tools', 'AssetPipeline', 'staging',
                                                      'scene_nb', 'backbar.png'))


# 'window' runs AFTER 'room': it reads the shipped room's alpha to find its own hole.
RECIPES = {'room': post_room, 'window': post_window, 'counter': post_counter,
           'plants': post_plants, 'taps': post_taps, 'tables': post_tables,
           'backbar': post_backbar}


def measure(only):
    for f in sorted(os.listdir(SRC)):
        p = os.path.join(SRC, f)
        im = Image.open(p)
        print('%-24s %-5s %9s  aspect %.3f' % (f, im.format, '%dx%d' % im.size,
                                               im.width / im.height))
    print('\npalette: %d colours from UITheme.cs' % len(PAL))


def main():
    global PAL, SRC
    argv = sys.argv[1:]
    if '--quantize' in argv:
        globals()['QUANTIZE'] = True
        argv.remove('--quantize')
    if '--src' in argv:
        i = argv.index('--src')
        SRC = argv[i + 1]
        del argv[i:i + 2]
    PAL = palette()
    cmd = argv[0] if argv else 'measure'
    only = argv[1:]
    if cmd == 'measure':
        measure(only)
        return
    for key, fn in RECIPES.items():
        if only and key not in only:
            continue
        print('[%s]' % key)
        fn()


if __name__ == '__main__':
    main()
